### ISSUE TITLE
Example input

### ISSUE THREAD

**Issue by jaanos** [dkegle/lvr201718#1]
Please specify in `README.md` which of the input files is the one you are choosing as your example (i.e., the one that best shows the strengths of your SAT solver).

**Comment by dkegle** [comment]
Specified, graph-1000-2000-3.txt, in root dir.

**Comment by jaanos** [comment]
Thanks, linked as of jaanos/LVR@5285ce06ca5ae1d60587ee7c0f984dd732b272a9.
